from enum import Enum

class IGElement(Enum):
    AIM = 1
    ATTRIBUTE = 2
    ATTRIBUTE_PROPERTY = 3
    OBJECT_DIRECT = 4
    OBJECT_DIRECT_PROPERTY = 5
    EXEC_CONSTRAINT = 6
    SEPARATOR = 7
    DEONTIC = 8
    ACTIVATION_CONDITION = 9
    CONSTITUTED_ENTITY = 10
    CONSTITUTED_FUNCTION = 11
    CONSTITUTING_PROPERTIES = 12
    CONSTITUTED_DEONTIC = 13
    CONSTITUTED_CONTEXT = 14
    CONSTITUTED_SEPARATOR = 15
    CONTEXT = 16