from enum import Enum


class IGElement(Enum):

    AIM = 1
    ATTRIBUTE = 2
    ATTRIBUTE_PROPERTY = 3
    OBJECT = 4
    OBJECT_PROPERTY = 5
    DEONTIC = 6
    SEPARATOR = 7
    CONTEXT = 8

    CONSTITUTED_ENTITY = 9
    CONSTITUTED_ENTITY_PROPERTY = 10
    CONSTITUTIVE_FUNCTION = 11
    CONSTITUTING_PROPERTIES = 12
    CONSTITUTING_PROPERTIES_PROPERTY = 13
    MODAL = 14
    CONSTITUTED_CONTEXT = 15
